services:
    database:
        name: Start backend
        commands:
            start: npm start
tasks:
  installDependencies:
    name: Install Dependencies
    command: npm install
    triggeredBy:
      - postEnvironmentStart
  runTests:
    name: Run Tests
    command: npm test
    triggeredBy:
      - manual
