tasks:
    hello:
        name: NPM install
        command: |
            npm install
        triggeredBy:
        - manual
    again:
        name: Start app
        command: |
            npm start
        triggeredBy:
        - manual