tasks:
  install:
    name: Install dependencies
    command: npm install
    triggeredBy:
      - postEnvironmentStart

  start:
    name: Start development server
    command: npm start
    triggeredBy:
      - manual

  test:
    name: Run tests
    command: npm test
    triggeredBy:
      - manual